#!/bin/bash

c_flag=false # comparison between documented vs original file

# check if c_flag is present
while getopts "c" opt; do
  case ${opt} in
    c ) c_flag=true ;;
    \? ) echo "Invalid option"; exit 1 ;;
  esac
done

FILES=$(git diff --name-only --cached)

python3 doc.py "${FILES}"

for FILE in $FILES; do
    NAME="${FILE%.*}"
    EXT="${FILE##*.}"

    if $c_flag; then
        NEW_FILE="${NAME}_documented.${EXT}"
        TMP_FILE="${NAME}_temp.${EXT}"
        sdiff "${FILE}" "${NEW_FILE}" -o "${TMP_FILE}"
        rm "${FILE}"
        rm "${NEW_FILE}"
        mv "${TMP_FILE}" "${FILE}"
    fi
done

